### ISSUE TITLE
GAMA 1.9.2 - Anpassung des Workshop-Modells

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/q100_abm_TREND#105]
Bitte workshop fork (der Vollständigkeit halber) auf 1.9.2 optimieren:

https://github.com/lwinkeler/q100_abm_qscope-workshop 

____________________
@dunland anschließend müsste dann wohl auch der Q-Scope entsprechend nochmal gecheckt werden, dass daraus keine unerwarteten Folgeprobleme resultieren, richtig?

**Comment by phiola** [comment]
Sollte jetzt wieder laufen. Siehe https://github.com/quarree100/q100_abm_TREND/commit/3ac58bc658db79bfef874f8a9114d18b19f41eb2 .

**Comment by lwinkeler** [comment]
Nice!

- [ ] Kannst du das bestätigen @dunland?; anschließend kann das issue sehr gerne geschlossen werden <3

**Comment by dunland** [comment]
Lokal funktioniert es bei mir. Ich prüfe es gleich auf dem Q-Scope ‒ muss dafür noch 1.9.2 installieren.
Würde dann **final** main<--182 mergen und dann pre_main in GAMA_1.8.2 umbenennen. Dann haben wir einen funktionierenden main-branch und einen Backup-1.8.2-Branch

**Comment by dunland** [comment]
erledigt!
