### ISSUE TITLE
Workshops in Heide: Logistik qScope

### ISSUE THREAD

**Issue by lwinkeler** [quarree100/q100_abm_TREND#74]
Organisieren von:

- [x] Transport qScope (inkl. Transportsicherheit)
- [x] Ggf. Redundanzen einplanen (wird ein zweiterer Spiegel benötigt?)
- [x] Wie ist der Zeithorizont?
- [x] Ist alles vor Ort was benötigt wird?

**Comment by dunland** [comment]
11.08.: Teike kümmert sich um Räumlichkeiten: 
- es  steht wohl nur noch ein Raum in der FH zur Verfügung 
- Am 15.9. ist der Raum noch  09:30 bis 10:30 belegt → Teike versucht herauszufinden, ob wir zwecks Aufbau schon am 14.9. abends in den Raum können.. Sonst wird der Aufbau zu knapp! 
- Abbau Fr Abend nach der Veranstaltung (?)

**Comment by lwinkeler** [comment]
> Hallo in die Runde,
>  
> das mit dem Raum bei der FH klappt. Er eignet sich für 15 Personen. Bei 20 Personen wird es sehr eng.
> Es stehen zwei Smartboards zur Verfügung. Aufbau am Mittwoch wäre ebenfalls kein Problem.
>  
> Bei Bedarf kann vor Ort ein minimalistisches Catering (Kaffee, Tee, Wasser, Kekse) angeboten werden, mit der Bitte dann ggf. den Kaffeevorrat wieder aufzufüllen. Wir können aber gerne auch selbst Kuchen etc. mitnehmen und dort bereitstellen. Geschirr ist vorhanden.
>  
> Ich habe mit Herrn Huusmann verabredet, dass im Vorfeld nochmal die Details (genaue Zeiten, Catering etc.) abgestimmt wird.
>  
> Viele Grüße
>  
> Teike

**Comment by lwinkeler** [comment]
> Sehr geehrte Frau Fischer,
>  
> herzlichen Dank für das eben geführte Telefonat mit Ihnen.
>  
> Wir würden gern den von Ihnen für uns reservierten Sprinter Maxxi mit den Maßen 3,60 x 1,74 x 1,85 (Höhe) für 3 Personen vom 09.11.-11.11.22 für einen Transport von Bremen nach Heide (Holstein) und zurück mit der Versicherung und Selbstbeteiligung in Höhe von € 70,00 buchen.
>  
> Lennart Winkeler wird den Wagen fahren und er wird ihn gegen 7:30 Uhr am 09.09. abholen.
> David Unland und Philipp Eppe werden die Beifahrer sein.

_____________________________

> Der Wagen ist gemietet vom 09.11. - 7 Uhr morgens  und muss spätestens um 7 Uhr morgens am 12.11. auf dem Hof stehen. Das passt.
>  
> Die Uni ist am Wochenende geschlossen. Aber: man kann eine mail an [leitwarte@uni-bremen.de](mailto:leitwarte@uni-bremen.de)  schicken und sie bitten zu einer bestimmten Uhrzeit das SFG aufzuschliessen. Generell wird die Uni rund um die Uhr „bewacht“. Das bedeute, nachts sind hier Sicherheitskräfte und drehen ihre runden.
>  
> Falls du dann nicht pünktlich zurück bist, gibt es die Leitwarte, die du dann anrufen könntest und denen  du Bescheid gibst.
> Das ist die UNI Nummer 2400. Die wirklich nur anrufen, wenn was ist, da die auch im Notfall angerufen wird.
> (0421-2182400)- Aber wie gesagt, hier in unserem Fall kannst du die anrufen. Die ist immer besetzt; es sei denn, der Menschmacht gerade seine runde. Dann musst du halt warten.
>  
> Vg
> Ingrid

zur Info @dunland

**Comment by lwinkeler** [comment]
**Ansprechpartner der FH Westküste:**

Dipl.-Ing. (FH) Stefan Huusmann

Raum: LAG 053.03
Tel.:  0481 - 8555 352
E - Mail: [huusmann@fh-westkueste.de](mailto:huusmann@fh-westkueste.de)

**Comment by lwinkeler** [comment]
[Anfahrtsskizze FH Westküste.pdf](https://github.com/quarree100/q100_abm/files/9949650/Anfahrtsskizze.FH.Westkuste.pdf)

**Comment by dunland** [comment]
## Mitnehmen:
- Staublappen
- Werkzeugkoffer +Inbusschlüssel
- Arbeitshandschuhe, Arbeitshose
- Schaumstoff/Decken für Transport?
- Gaffa-Tape + weißes Papier zum Abkleben von Reflexionen usw
- Acrylkleber, Farben, Plättchen
- Webcam, Digitalkamera zur Dokumentation

**Comment by PhilippEppe** [comment]
Ich werde noch meine Kamera für die weitere Fotodokumentation mitnehmen.

**Comment by dunland** [comment]
- Badehose
- Badelatschen
- Champagner

**Comment by dunland** [comment]
# für Heider Zukunftsgespräch am 11.05.23:

- 17:30 offizieller Beginn
- vorher inoffiziell mit PTJ+Politik?

## Logistik:
- [ ] Auto
    - [ ] Ingrid informieren
- [ ] Sicherheitsdienst Uni informieren über späte Rückkehr

## Inhaltlich
- Ablauf testen
- für Grüne-Wiese-Modus: Simulation kürzen auf 5-10 Jahre
- Update Energiemarktgrundlage?

## Hardware
- [ ] slider fixen
- [ ] rechter Tisch stand schief?!
- [ ] Montage Rückwand?!

## Mitbringen

- Strom-Verlängerungskabel
- Staublappen
- Werkzeugkoffer +Inbusschlüssel
- Arbeitshandschuhe, Arbeitshose
- Schaumstoff/Decken für Transport?
- Gaffa-Tape + weißes Papier zum Abkleben von Reflexionen usw
- ~Acrylkleber, Farben, Plättchen~
- ~Webcam, Digitalkamera zur Dokumentation~


KW | Tag | What
-----|---------|----------
15 | 14.04. | Ablauf-Brainstorming
16 | jeden | LW Bildungszeit
17 | |
18 | |
19 | 10.05. | Abbau im Büro
19 | 11.05. | vor 17:30: inoffizieller Beginn
19 | 11.05. | 17:30 offizieller Beginn

**Comment by lwinkeler** [comment]
Einen Punkt würde ich gerne noch hervorheben, der gerade noch in den Sinn kam: Zu zwei war es etwas schwer, die Rückwand in/aus den/m Transporter zu heben.
Da sollten wir uns ggf. noch ein Workaround überlegen.

**Comment by dunland** [comment]
Montage Rückwand = anbringen der übrigen Klappen, Türen und Deckel

Habe für Transport bei Ingrid/Schlohbohm nach einer Laderampe gefragt.

**Comment by lwinkeler** [comment]
# Infos zur Anfahrt:

Aussage LW:
> 1.	Wie besprochen versuchen David und ich zwischen 13:00 und 14:00 Uhr in Heide zu sein. Ob Torben dann auch bereits dabei ist, oder er separat mit dem Zug anreist ist aktuell noch nicht klar. Das nur zur Info, falls es noch Sachen zu besprechen gäbe.

**Antwort Nele**
Zu der Uhrzeit bin ich bei der Stiftung Mensch, um das Sommerfest zu planen. Aber Herr Richardt (IT-Admin des BBZs) hat mir versichert, dass das Gebäude offen und die Geschäftsstelle vor Ort ist. Hier sind die Kontaktdaten, falls ihr die benötigt. Ich kündige euch auf jeden Fall auch noch mal an. In der Nähe des von mir vorgeschlagenen Standorts gibt es eine Steckdose und Wifi gibt es auch. Es gibt leider keine Vorhänge oder Ähnliches, aber wir sind auf jeden Fall auf der Ostseite. 
Christiane Maschke: 0 48 32 / 903 - 102
Tim Reichardt:  0481 85081-18 
BBZ Dithmarschen Heide, Rungholtstraße 2c 25746 Heide ((04 81) 8 50 81 – 0)

![asd](https://user-images.githubusercontent.com/70899694/236215194-242111b4-109b-4a7f-9f06-21a85b943c48.png)

Unter der Adresse gibt es leider mehrere Gebäude, mir wird bei Google Maps das an der Ecke angezeigt. Wir sind in dem großen mit dem roten Kreuz. Ich sorge auf jeden Fall dafür, dass alles gut ausgeschildert ist.
